version: 1.9.9.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v141_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\Explorer\projects\VC2015\
    - msbuild Explorer.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            Push-AppveyorArtifact "Explorer\projects\VC2015\$env:PLATFORM\$env:CONFIGURATION\Explorer.dll" -FileName Explorer.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" ) {
            Push-AppveyorArtifact "Explorer\projects\VC2015\$env:CONFIGURATION\Explorer.dll" -FileName Explorer.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "Explorer_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\Explorer\projects\VC2015\$env:PLATFORM_INPUT\$env:CONFIGURATION\*.dll"
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "Explorer_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName "$($env:APPVEYOR_BUILD_FOLDER)\Explorer\projects\VC2015\$env:CONFIGURATION\*.dll"
            }
        }

artifacts:
  - path: Explorer_*.zip
    name: releases
